app:
    id: ${spring.application.name}
apollo:
    bootstrap:
        enabled: true
server:
    port: 6130
    undertow:
        accessLog:
            enabled: true
            pattern: "%t %a \"%r\" %s (%D ms)"
            dir: /var/lux/logs/${spring.application.name}
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
    application:
        name: common
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: dbcp1
            connection-test-query: select 1
            username: root
            password: jiangtai
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: 3000
        pool:
            max-idle: 10
            max-wait: 10000
        max-active: 20
        maxTotal: 20
#        password: crs-95idx3hg:JTdevTEST(!13)8E
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                    logs: target/elasticsearch/log
                    data: target/elasticsearch/data
        throw-exception-if-no-handler-found: true
    mvc:
        static-path-pattern: /**
    resources:
        static-locations:  classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    http:
        multipart:
            maxFileSize: 1000Mb
            maxRequestSize: 1000Mb
    output:
      ansi:
        enabled: always
    session:
      store-type: none
    thymeleaf:
      cache: false
management:
    security:
        enabled: false
logging:
    level:
        root: INFO
mybatis:
    type-aliases-package: com.jt.lux.entity
    mapper-locations: classpath:mapper/*.xml
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://10.10.32.54:8761/eureka
    instance:
        prefer-ip-address: true
        hostname: ${spring.cloud.client.ipAddress}
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
feign:
    hystrix:
        enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 30
      maximumSize: 50
      allowMaximumSizeToDivergeFromCoreSize: true
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 1000000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000
jtpf:
    logging:
        name: common
        level: DEBUG
        pattern: "%red(%d) %highlight(%level) %green([%thread]) %boldMagenta(%logger{48}): %msg%n"
        dir: /var/lux/logs/${spring.application.name}
        logstash:
            destinations: "172.16.4.147:35610"
    wx:
        jscode2session: https://api.weixin.qq.com/sns/jscode2session
        APPID: wx18e2f7868d2a3949
        SECRET: 3e3d0f2b66a6d27b9a8295eccdaf770b
        token: xingshhwx90503991
        gettokenurl: https://api.weixin.qq.com/sns/oauth2/access_token
        getAccessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
        getticket: https://api.weixin.qq.com/cgi-bin/ticket/getticket
