server:
    port: 6130
    undertow:
        accessLog:
            enabled: true
            pattern: "%t %a \"%r\" %s (%D ms)"
            dir: /var/lux/logs/${spring.application.name}
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
    application:
        name: common
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://39.106.157.114:3306/test_yougu?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: dbcp1
            connection-test-query: select 1
            username: test_yougu
            password: 5t3)testoq0cJrpu4!
    redis:
        host: 39.106.157.114
        port: 6379
        timeout: 30000
        pool:
            max-idle: 10
            max-wait: 10000
        max-active: 20
        maxTotal: 20
        password: crs-95idx3hg:JTdevTEST(!13)8E
    mvc:
        static-path-pattern: /**
    resources:
        static-locations:  classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    http:
        multipart:
            maxFileSize: 1000Mb
            maxRequestSize: 1000Mb
    servlet:
        multipart:
            max-request-size: 1000MB #总文件大小
            max-file-size: 1000MB #单个文件大小
    output:
      ansi:
        enabled: always
    session:
      store-type: none
    thymeleaf:
      cache: false
    main:
      allow-bean-definition-overriding: true
swagger:
  enabled: true
management:
    security:
        enabled: false
logging:
    level:
        root: INFO
mybatis:
    type-aliases-package: com.yg.lux.entity
    mapper-locations: classpath:mapper/*.xml

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://10.10.32.54:8761/eureka
    instance:
        prefer-ip-address: true
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
feign:
    hystrix:
        enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 30
      maximumSize: 50
      allowMaximumSizeToDivergeFromCoreSize: true
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 1000000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000
aliyun:
    sms:
        accessKeyId: LTAI5tRyeotzLHuZhTj5kdde
        accessKeySecret: hDgNuBCoRfr66xVHKI0KRQIJ5pAfON
        templateCode: SMS_227735325
        templateCode2: SMS_215351161
        templateCode3: SMS_238135237
    oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        accessKeyId: LTAI5tRyeotzLHuZhTj5kdde
        accessKeySecret: hDgNuBCoRfr66xVHKI0KRQIJ5pAfON
        bucketName: yougufiles
        maxFileSize: 1000  #MB
jtpf:
    logging:
        name: com.yg.lux
        level: DEBUG
        pattern: "%red(%d) %highlight(%level) %green([%thread]) %boldMagenta(%logger{48}): %msg%n"
        dir: /var/lux/logs/${spring.application.name}
        logstash:
            destinations: "172.16.4.147:35610"
    defaultPasswod: 123456
    cron:
      #在启动参数中设置以下配置
      oneminute: 0 0 1 * * ?
      oneminute2: 0 4 9 * * ?
      fiveminute: 0 0 1 * * ?
      method4: 0 59 23 * * ?
      method5: 0 30 11 * * ?
      onehour: 0 */1 * * * ?
    wx:
        jscode2session: https://api.weixin.qq.com/sns/jscode2session
        APPID: wx9305f3490d07f4d3
        SECRET: 6a4f9e991e72d74890a3880d6990cc84
        gettokenurl: https://api.weixin.qq.com/sns/oauth2/access_token
        getAccessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
        getticket: https://api.weixin.qq.com/cgi-bin/ticket/getticket
        grantType: getticket
    token:
      redisExpiresInMinutes: 10080
      accessTokenExpiresInMinutes: 525600
      refreshTokenExpiresInMinutes: 525600
    idg:
      workerId: ${IDG_WORKER_ID:1}
      workerIdConf: assign
    jwt_secert: jwt_secert
    ocr:
      secretId: AKIDPZY8csgXx86sT3HeaPQDk2Cj9KvHEq32
      secretKey: tb4sTikZswlwseBTWLyFepoY42lFVAUa
      idCardUrl: https://ocr.tencentcloudapi.com
    secret: common

app:
    id: ${spring.application.name}
    auth:
        # 用于验证token有效性的uri
        checkUri: /api/check
        # 用于获取access_token的uri
        accessTokenUri: /api/access_token
        # 用于刷新access_token的uri
        refreshTokenUri: /api/refresh_token
        userloginUri: /api/v1/userLogin
        smsUri: /api/v1/sendSMS
        registerUri: /api/v1/register
        uploadFileUri: /api/v1/uploadFile
        scanOCRUri: /api/v1/scanOCR
    special-uri:
        # 黑名单
        blackList:
            /auth-svc/123,/auth-svc/124
        # 白名单
        whiteList:
            /swagger-demo/**/*
            ,/jtpf/swagger-demo/**/*
            ,/**/swagger-ui.html*
            ,/**/swagger-ui.html*/**/*
            ,/**/swagger-resources*
            ,/**/swagger-resources/*
            ,/**/swagger-resources/**/*
            ,/**/v2/api-docs*
            ,/**/v2/api-docs/**/*
            ,/favicon.ico
            ,/**/*.htm
            ,/**/*.html
            ,/**/*.js
            ,/**/*.jpg
            ,/**/*.jpeg
            ,/**/*.gif
            ,/**/*.css
            ,/**/*.png
        # 灰名单，获取用户身份，但不校验权限
        grayList:
            /123/456